version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: comments_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: UTC
      PGTZ: UTC
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: comments_db
      JWT_SECRET: supersecretkey
      JWT_EXPIRES_IN: 7d
      NODE_ENV: development
      PORT: 3001
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - db
    ports:
      - '3001:3001'
    command: npm run start:prod

  frontend:
    build: ./frontend
    restart: always
    environment:
      REACT_APP_API_URL: https://comments.webark.in/api/v1
    depends_on:
      - backend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    command: npm start

volumes:
  db_data: 
